project:
  type: website
  output-dir: docs
  resources:
    - static/h5p-test.html
    - h5p/

website:
  title: "JChev"
  sidebar:
    logo: images/JCLogoBl.png
    style: "docked"
    search: true
    contents:
      - href: index.qmd
        text: Home
        icon: bi-house
      - href: cv.qmd
        text: CV
        icon: bi-file-person
      - href: projects.qmd
        text: Projects
        icon: bi-list
      - href: driverdiagram.qmd
        text: ADRD Driver Diagram
        icon: bi-grid-1x2
      - href: static/h5p-test.html
        text: H5P Timeline for Arthritis
        icon: bi-arrow-clockwise
        target: _blank

format:
  html:
    theme:
      - flatly
    css: styles.css
    toc: true

editor: visual

